apiVersion: v1
kind: Service
metadata:
  name: chat-svc
  namespace: ecoprompt
  labels:
    app: chat
    app.kubernetes.io/part-of: ecoprompt
spec:
  type: ClusterIP
  selector:
    app: chat
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
